### ISSUE TITLE
about long sequences generation

### ISSUE THREAD

**Issue by Zijing5** [zdchan/artigrasp#2]
Hello,I am a beginner in this filed.
I read your paper and saw that your method "can generate long motion sequences in environments with multiple object" and I wonder how long the generation can be? Or where I can find configuration about this in your code? I did not find any configuration parse like "n_frames" or "seq_len".
I will appreciate it a lot with your reply.

**Comment by zdchan** [comment]
Hi,

Thanks for the interest in our work. The sequence length is controlled by n_steps_r in each .py script, just as https://github.com/zdchan/artigrasp/blob/6f6305ce4897e5577bfb410f1bda301f97b9e326/raisimGymTorch/raisimGymTorch/env/envs/compose_eval/compose_eval.py#L336C25-L336C25. In general, the length can be as long as you want. But intuitively, it depends on the phases of the motion you want to generate, just as determined by a heuristics-based planner in our paper. 

Best,
Hui
