### ISSUE TITLE
Cannot find mesh

### ISSUE THREAD

**Issue by zhoujun-7** [zdchan/artigrasp#3]
Hello, 

Thanks for your exciting work.

I ran the interactive visualizations `raisimUnity/linux/raisimUnity.x86_64` in the `artigrasp` directory and clicked Connect bottom. However, nothing was shown in the window, but error texts `System Exception: Connot find mesh from the resource directories = ./meshes/right_wirst.stl`.

Do I lack some resource files?

Looking forward to your reply!

BR!
Jun

**Comment by zdchan** [comment]
Hi Jun,

Thanks for your question. It's a bit strange with this problem. Have you checked the Auto-connect option?
![image](https://github.com/zdchan/artigrasp/assets/26100670/7a4f740d-00fb-43d9-b596-0a46a2d0264d)
And have you changed anything? Does the runner_eval.py shows any error?

Best,
Hui

**Comment by zhoujun-7** [comment]
Hi Hui,

Thanks fro you reply. I had checked the Auto-connect option but got the same problem.
![Screenshot from 2023-12-07 18-03-22](https://github.com/zdchan/artigrasp/assets/101878152/51e2dbcd-7240-47e1-b978-1ef0b135447f)


I followed [INSTALLATION](https://github.com/zdchan/artigrasp/blob/main/docs/INSTALLATION.md) to configure my environment.

The runner_eval.py seem to be normal.
![Screenshot from 2023-12-07 18-04-17](https://github.com/zdchan/artigrasp/assets/101878152/681d2ede-2b0e-43dd-8cb5-ca454c7ce59e)

But the command `sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils` was not passed. Is this the key to the problem?

Sincerely,
Jun

**Comment by zdchan** [comment]
Hi Jun,

VulKan is the render API of raisim. As you can run runner_eval.py normally, the problem should come from the simulation visualization side. The failure of `sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils` may be the reason. Could you try to pass this command and check whether this solve the problem? Please tell me if it doesn't help. 

Best,
Hui

**Comment by zhoujun-7** [comment]
Hi Hui,

Thanks for your advice. Yesterday, I tried to install vulkan-utils by the command `sudo apt install valkan-utils`. But failed. I think that valkan-utils cannot be install on Ubuntu 22.04. 

Today, I change the OS of my PC to Ubuntu 20.04, and valkan-utils is installed successfully. It seems all commands in [INSTALLATION.md](https://github.com/zdchan/artigrasp/blob/main/docs/INSTALLATION.md#installation-guide) are passed. However, RaisimUnity still shows nothing but the error text, which is same with the case I occurred yesterday.

Here are the information of my PC.
CPU: i7 8700
GPU: RTX 2080Ti
OS: Ubuntu 20.04.6
CUDA: 12.2

BR,
Jun

**Comment by zdchan** [comment]
Hi Jun,

I have just checked the resource files and found I mistakenly forgot to upload .stl files. I have just loaded them so you should be able to see the visualization now after git pull. 

I am sorry for the mistake and thank you for pointing this out! Please tell me if you have any other questions. Otherwise I will close this issue.

Best,
Hui

**Comment by zhoujun-7** [comment]
Hi Hui,

I cloned the latest repository and ran the commands again. The RaisimUnity showed a different error which can be seen as follow.
![Screenshot from 2023-12-08 17-07-11](https://github.com/zdchan/artigrasp/assets/101878152/00b16d53-9885-4abb-b44f-48377ad95ad3)

Note that, the .stl file name is different. That means we are on the right direction. :+1:

Regards,
Jun

**Comment by zdchan** [comment]
Hi Jun,

Should be good now. Thanks!

Best,
Hui

**Comment by zhoujun-7** [comment]
Hi Hui,

Many thanks for your patience to help me solve the problem! Now the visualization is good.

Sincerely,
Jun

**Comment by zdchan** [comment]
Have fun with it!
