### ISSUE TITLE
API of general_two

### ISSUE THREAD

**Issue by zhoujun-7** [zdchan/artigrasp#4]
Hi Hui,

Thanks for sharing the codes. This project is very interesting. But I'm not sure how the `raisimGymTorch.env.bin.genral_two` works. Will you release the codes of `raisimGymTorch.env.bin.genral_two` or provide its API?

Regards,
Jun

**Comment by zdchan** [comment]
Hi Jun,

The bin under env is the built environments with `python setup.py develop`. You can check the setup.py to see how it's generated. All the general_two environment related codes are under `envs/general_two`, which includes the .cpp environment and .py training/evaluation script, and a .yaml file for the parameters.

Best,
Hui

**Comment by zhoujun-7** [comment]
Thanks for your helpful reply.
