### ISSUE TITLE
How to run this on a headless ubuntu server?

### ISSUE THREAD

**Issue by gmindflow** [zdchan/artigrasp#5]
Hi, thank you for sharing your great work.
I am new to using a raisim physics simulator and I have a question.

If I'm correct to run the raisim physics simulator, I need to have a monitor display directly connected to the machine, right?
Do you happen to know any way I can run this simulator on my headless ubuntu server, while displaying the simulation on my local computer which is connected via internet with the ubuntu server?

Would be some great help if you can give me some advice, thanks!

**Comment by zdchan** [comment]
Hi @gmindflow ,

Thanks for your interest in our work. I have not tried this before. It's a question about raisim, so you may check their github [issues](https://github.com/raisimTech/raisimLib/issues). But I found a related [question](https://github.com/raisimTech/raisimLib/issues/515#issuecomment-1773637970). It's impossible to run unity and connect port in Docker, so I guess it may be the same for the server? Hope this helps

Best,
Hui
