### ISSUE TITLE
No file Named 'label_gen_new.py"

### ISSUE THREAD

**Issue by isabella4444x** [zdchan/artigrasp#6]
Hello,
 In the "raisimGymTorch/raisimGymTorch/env/envs/left_fixed/runner.py",line 180
"saver = ConfigurationSaver(log_dir=exp_path + "/raisimGymTorch/" + args.storedir + "/" + task_name,
                           save_items=[task_path + "/cfgs/" + args.cfg, task_path + "/Environment.hpp",
                                       task_path + "/runner.py", task_path + "/../../../helper/label_gen_new.py"], test_dir=test_dir)"
but there is no file named "label_gen_new.py " while there is only a "label_gen_final.py" which appears in the same place of the ruuner.py   of right hand's trainning

Is this a typing error？Or where is the"label_gen_new.py"?

Looking forward to your reply!

**Comment by zdchan** [comment]
Hi Jinxian,

Thanks for pointing this out and yeah it's a typo. This line aims to back up the related code and label_gen_new was a previous version. I forgot to change this line to back up. You can just change it to label_gen_final. I will also update the code. Thanks!

Best,
Hui

**Comment by isabella4444x** [comment]
Hi Hui,
Thanks for your reply!But something else made me confused .

When I went through the process of evaluation, I met the problem that files "pos_bias.txt" and "angle_bias.txt" missing which should be in the director named "data_all" .
So how can I get the "pos_bias.txt" and "angle_bias.txt" or the data pos_bias and angle_bias?

Looking forward to your reply!

**Comment by zdchan** [comment]
Hi Jinxian,

pos_bias and angle_bias and just randomly sampled targets for evaluation. You can find the way to generate them [here](https://github.com/zdchan/artigrasp/blob/68e8a092d441025ecbfdae0fb97afb8c25d6a3bc/raisimGymTorch/raisimGymTorch/env/envs/compose_eval/ketchup_eval.py#L288). I just saved the sampled bias as .txt files for a fair comparison. You can generate your own bias, or I can also share you mine if you need.

Best,
Hui
