### ISSUE TITLE
bug about run the demo

### ISSUE THREAD

**Issue by GuanHY** [zdchan/artigrasp#7]
when I run the demo <python raisimGymTorch/env/envs/general_two/runner_eval.py>,it shows some errors about environment definition.
![1](https://github.com/zdchan/artigrasp/assets/53296096/3071c80a-7b39-4df8-8026-7612a18ca435)
![2](https://github.com/zdchan/artigrasp/assets/53296096/f7fdba08-8904-48b3-9c42-7e07bc073d74)
After I modified the code according to the instructions, the following error still occurred
![3](https://github.com/zdchan/artigrasp/assets/53296096/1ddcfbce-2aba-4bea-9bcb-e61653a916cb)
![4](https://github.com/zdchan/artigrasp/assets/53296096/387d4d7a-d1bb-4e56-ac95-d4d4e2f3c9c0)

**Comment by zdchan** [comment]
Hi @GuanHY ,

Thanks for the interest in our work! I guess this is caused by the ruamel.yaml package version. The one I am using is ruamel.yaml 0.17.16. Could you maybe have a try whether this helps?

Best,
Hui
